### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by steamvinstudios** [pinokiocomputer/pinokio#118]
https://github.com/pinokiocomputer/pinokio/assets/54758623/53c90adc-1314-4a6b-989e-c7280b5f77db

**Comment by Tom60chat** [comment]
Appears when installing Stable Video Diffusion.

```python
Traceback (most recent call last):
  File "C:\Users\Tom60\pinokio\bin\miniconda\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\conda\cli\main.py", line 128, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 388, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 20, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 51, in handle_exception
    from .exceptions import (
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\conda\exceptions.py", line 15, in <module>
    import requests
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\urllib3\connectionpool.py", line 15, in <module>
    from ._request_methods import RequestMethods
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 284, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\Tom60\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 294, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'
```

**Comment by Mantinum** [comment]
Hello, same issue despite a complete reinstallation of Anaconda, Miniconda, and Visual Studio.

**Comment by skywoker74** [comment]
> 2024-02-12.18-40-37.mp4

What I did to make it work:
1. Downloaded and installed Pinokio Setup 0.2.18. Then I installed BRIA RMBG and all components were installed with it.
2. Download and run Pinokio-1.1.0 to update the version
It worked for me.
