### ISSUE TITLE
Stable Cascade, Bria RMBG, and others failing during start - Ubuntu 22.04, Pinokio-1.1.0.AppImage

### ISSUE THREAD

**Issue by josephrocca** [pinokiocomputer/pinokio#129]
Reproduction steps:
1. Fresh Ubuntu 22.04 install
2. Download `Pinokio-1.1.0.AppImage`
3. `chmod +x Pinokio-1.1.0.AppImage`
4. `./Pinokio-1.1.0.AppImage`
5. I chose my non-OS inbuilt SSD drive as 'home': `/media/joe/extradrive1/pinokio`
6. Install Stable Cascade (or Bria) - install is successful.
7. Click "start"
8. See these logs:
```
<<PINOKIO SHELL>> source /media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/bin/activate /media/joe/extradrive1/pinokio/api/stablecascade.git/app/env && python app.py
Traceback (most recent call last):
  File "/media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/media/joe/extradrive1/pinokio/bin/miniconda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/joe/extradrive1/pinokio/api/stablecascade.git/app/app.py", line 6, in <module>
    import torch
  File "/media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/media/joe/extradrive1/pinokio/api/stablecascade.git/app', '/media/joe/extradrive1/pinokio/bin/miniconda/lib/python310.zip', '/media/joe/extradrive1/pinokio/bin/miniconda/lib/python3.10', '/media/joe/extradrive1/pinokio/bin/miniconda/lib/python3.10/lib-dynload', '/media/joe/extradrive1/pinokio/api/stablecascade.git/app/env/lib/python3.10/site-packages']
(env) <<PINOKIO SHELL>> 
[Start proxy] Local Sharing {{input.event[0]}}
Proxy Started
```

**Comment by josephrocca** [comment]
I saw that `Pinokio-1.2.0.AppImage` has released and just tried it, and still get the same error 😢

```
<<PINOKIO SHELL>> source /home/joe/pinokio/api/dust3r.git/app/env/bin/activate /home/joe/pinokio/api/dust3r.git/app/env && python demo.py --device cuda --weights checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth
Traceback (most recent call last):
  File "/home/joe/pinokio/api/dust3r.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/joe/pinokio/bin/miniconda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joe/pinokio/api/dust3r.git/app/demo.py", line 11, in <module>
    import torch
  File "/home/joe/pinokio/api/dust3r.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/joe/pinokio/api/dust3r.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/joe/pinokio/api/dust3r.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/joe/pinokio/api/dust3r.git/app', '/home/joe/pinokio/bin/miniconda/lib/python310.zip', '/home/joe/pinokio/bin/miniconda/lib/python3.10', '/home/joe/pinokio/bin/miniconda/lib/python3.10/lib-dynload', '/home/joe/pinokio/api/dust3r.git/app/env/lib/python3.10/site-packages']
(env) <<PINOKIO SHELL>> 
[Start proxy] Local Sharing {{input.event[0]}}
Proxy Started {"target":"{{input.event[0]}}","proxy":"http://10.0.0.15:8001"}
```

This time I chose `/home/joe/pinokio` as my data directory instead of a directory in my mounted SSD, so the issue isn't related to install location, it seems.

@cocktailpeanut Can you please test the AppImage files on Ubuntu 22.04 before release? :pray:

**Comment by The-Nils** [comment]
same for me on all apps using the Pinokio-1.2.49.AppImage file
