### ISSUE TITLE
Pinokio installing Error: User did not grant permission

### ISSUE THREAD

**Issue by ProDigalShrimp** [pinokiocomputer/pinokio#138]
For some reason I can't get past this Error, does anyone know how to fix this?
![Capture](https://github.com/pinokiocomputer/pinokio/assets/162331974/0723a42c-780c-45b5-a00b-983061f09165)

Error: User did not grant permission. at C:\Users\My Pc\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\sudo-prompt-programfiles-x86\index.js:553:29 at ChildProcess.exithandler (node:child_process:430:5) at ChildProcess.emit (node:events:513:28) at maybeClose (node:internal/child_process:1091:16) at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by pixbalance** [comment]
Had the same issue. Starting Pinokio with admin rights did solve the problem.

**Comment by expertsdig** [comment]
Hi have the same problem, someone solved?

**Comment by techsd** [comment]
Hi! 
have the same problem, someone solved?

**Comment by moxx** [comment]
FYI: That's great I had the same problem, it seems to be due to special characters in the username so if the %USERPROFILE% contains special characters some python env stuff has problems with it. Then I tried to install anaconda and the same problem occurs. So renaming the user folder in windows is a pain, but it fixed this problem.

**Comment by dhosein** [comment]
Similar issue here:
![Screenshot 2024-08-27 085516](https://github.com/user-attachments/assets/4954de87-1d0d-43f0-8847-a7573c5e8ca3)

This is while 'running as admin' and correctly responding to the permissions popup.

**Comment by Oliver-bran** [comment]
Error
Error: User did not grant permission. at C:\Users\USUARIO\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\sudo-prompt-programfiles-x86\index.js:553:29 at ChildProcess.exithandler (node:child_process:430:5) at ChildProcess.emit (node:events:513:28) at maybeClose (node:internal/child_process:1091:16) at ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by Roysignaler** [comment]
I got past this error by installing vs manually. 

The solution ( [Manually install Visual Buildtools 2019 with Windows Powershell](https://github.com/6Morpheus6/pinokio-wiki?tab=readme-ov-file#4-manually-install-visual-buildtools-2019-with-windows-powershell) ) was given by @6Morpheus6 at https://github.com/pinokiocomputer/pinokio/issues/67
Cheers.
