### ISSUE TITLE
No module named 'uvicorn'

### ISSUE THREAD

**Issue by fazzam12345** [pinokiocomputer/pinokio#140]
i'm receving this error since the last update can't realy install anything:
C:\Users\fares\pinokio\bin\py>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && uvicorn --port 42001 server:app
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fares\AppData\Roaming\Python\Python310\Scripts\uvicorn.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'uvicorn'

**Comment by 7flash** [comment]
Same

**Comment by 7flash** [comment]
It's solved by adding "uvicorn" to requirements.txt inside of pinokio\api\pcm.git\app
