### ISSUE TITLE
No AMD Support?

### ISSUE THREAD

**Issue by 42Coding** [pinokiocomputer/pinokio#163]
It looks like there is no logic for AMD support right?
I wanted to use "Stable Diffusion web UI" with pinokio on my Ubuntu System and I get the error:
Traceback (most recent call last):
  File "/home/user/pinokio/api/automatic1111.git/app/launch.py", line 48, in <module>
    main()
  File "/home/user/pinokio/api/automatic1111.git/app/launch.py", line 39, in main
    prepare_environment()
  File "/home/user/pinokio/api/automatic1111.git/app/modules/launch_utils.py", line 386, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

After researching I found this article:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1742

And I also get the error "ENOENT: no such file or directory, stat '/home/user/pinokio/api/automatic1111.git/{{input.event[0]}}'" if I want to start the Web UI.

**Comment by ricperry** [comment]
Yeah, just about every app I try to install won't work. I can manually install these with my own venv, but I'm not experiencing luck with Pinokio. The Pinokio devs should let us configure some basic options, such as pytorch version, rocm or cuda, etc.... But I guess they're just another example of a dev unwilling to democratize AI.

**Comment by G3Kappa** [comment]
man I'm so tired of AMD being treated like a tenth class citizen. I get it, CUDA and all, but man if it isn't PAINFUL to wade through dozens of readmes and github repos only to find out that everyone assumes that I own a NVidia GPU.

**Comment by Gater73** [comment]
AMD support (ROCm) is done in the actual app ie. Stable Diffusion web UI not in pinokio, someone could build a workflow that sets that up automatically but that would make it not available for nvidia users, but i think there is sadly not enough AMD users that have the know how to make it. That could change with a release of zluda that actually works and its easy to install

**Comment by Pablohn26** [comment]
There is an amazing project named [rocm_sdk_builder](https://github.com/lamikr/rocm_sdk_builder) that could be integrated to allow AMD support

**Comment by thinwoodsman** [comment]
There are ROCM-enabled branches of PyTorch and bitsandbytes. Packages are provided, but I have only been able to get the ROCM versions to work with my card by compiling locally (after patching to add the model #). ROCM gets recognized as CUDA when an environment variable it set, so at runtime it is completely transparent to the app/model whether "torch.cuda" maps to CUDA or ROCM under the hood.

But this sort of edge case is where the "ship a copy of the developer's work environment" projects fail: I can produce a repaired version of a shared module or shared library, but if every project uses their own fetched-from-the-internet environment, be it Docker or Python Venv, then none of them will use the repaired version that I installed locally. The only way to get them to do so is to go into each  and rebuild its environment manually, and that time really is spent on other things - like writing Python apps to run the models from the command line, which will be much more stable over the long run.

Maybe some day in the far future when ROCM support is finally in the main branch of PyTorch, and all of these projects have been updated (yeah right) to use that version, it'll all "just work". Until, Pinokio joins the long list of AI projects that make too many assumptions to be usable.
