### ISSUE TITLE
OSError: [Errno 28] No space left on device - ??

### ISSUE THREAD

**Issue by Duemellon** [pinokiocomputer/pinokio#17]
I continue to get this error in some form or another after installation but during initial startup (when files are being downloaded) in different apps. My C: (boot drive) has no space (400mb or so) but my E: which I have setup for the target drive of Pinokio has 1.45TB or more. Is PInokio trying to use my C: for those run file downloads as a temp dir or something? 

OSError: [Errno 28] No space left on device
Downloading:  16%|████████████▍

**Comment by Axelaredz** [comment]
On Linux too error..

python venv already activate or run without venv: /home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.1
  Downloading https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl (2267.3 MB)
     ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━ 1.1/2.3 GB 5.0 MB/s eta 0:03:53
     ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

     ━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━ 1.1/2.3 GB 4.9 MB/s eta 0:03:53
Traceback (most recent call last):
  File "/home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/launch.py", line 48, in <module>
    main()
  File "/home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/launch.py", line 39, in main
    prepare_environment()
  File "/home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/modules/launch_utils.py", line 352, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "/home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/modules/launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "/home/axel/pinokio/api/sd-webui.pinokio.git/automatic1111/venv/bin/python3" -m pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118
Error code: 1
