### ISSUE TITLE
cannot run pip install

### ISSUE THREAD

**Issue by lanzjose** [pinokiocomputer/pinokio#180]
I am trying to install the requirements for two ComfyUI extensions (Photoshop plugin and the Hunyuan nodes)
Every time i try to run pip install -r requirements.txt or pip3 install -r requirements.txt, I get this error:

C:\Users\me\pinokio\api\comfyui.git\app\custom_nodes\HunyuanDiT>pip install -r requirements.txt
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Programs\Python\Python310\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip._internal.cli.main

What should I do to properly run this command?
Thank you!

**Comment by lanzjose** [comment]
C:\Users\me\pinokio\api\comfyui.git\app\custom_nodes\HunyuanDiT>python -s -m pip install -r requirements.txt
C:\Users\me\AppData\Local\Programs\Python\Python310\python.exe: No module named pip.__main__; 'pip' is a package and cannot be directly executed

C:\Users\me\pinokio\api\comfyui.git\app\custom_nodes\HunyuanDiT>
