### ISSUE TITLE
photomaker2 fails to run due to onnxruntime issue

### ISSUE THREAD

**Issue by nviraj** [pinokiocomputer/pinokio#190]
Error:

> Microsoft Windows [Version 10.0.22631.3880]
> (c) Microsoft Corporation. All rights reserved.
> 
> D:\Apps\pinokio\api\photomaker2\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && D:\Apps\pinokio\api\photomaker2\app\env\Scripts\activate D:\Apps\pinokio\api\photomaker2\app\env && python app.py
> 
> The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
> 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "D:\Apps\pinokio\api\photomaker2\app\env\lib\site-packages\insightface\__init__.py", line 8, in <module>
>     import onnxruntime
> ModuleNotFoundError: No module named 'onnxruntime'
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Apps\pinokio\api\photomaker2\app\app.py", line 16, in <module>
>     from face_utils import FaceAnalysis2, analyze_faces
>   File "D:\Apps\pinokio\api\photomaker2\app\face_utils.py", line 3, in <module>
>     from insightface.app import FaceAnalysis
>   File "D:\Apps\pinokio\api\photomaker2\app\env\lib\site-packages\insightface\__init__.py", line 10, in <module>
>     raise ImportError(
> ImportError: Unable to import dependency onnxruntime. 
> 
> (env) (base) D:\Apps\pinokio\api\photomaker2\app>
> 
> Disconnected...

**Comment by kkget** [comment]
ENOENT: no such file or directory, stat 'D:\pinokio\api\photomaker2.git\{{input.event[0]}}'

**Comment by zhanchenglin** [comment]
> ENOENT: no such file or directory, stat 'D:\pinokio\api\photomaker2.git{{input.event[0]}}'

你解决了这个问题吗？
