### ISSUE TITLE
cloudflared is not installed

### ISSUE THREAD

**Issue by luyishiliu8** [pinokiocomputer/pinokio#202]
cloudflared is not installed，how can i solve？thanks

**Comment by astrajpg** [comment]
same here

**Comment by asilvamaia** [comment]
Its possible to use my own domain to configure a Cloudlfare Tunnel?

**Comment by theboringhumane** [comment]
This is a issue when using a external ssd.

```sh
fatal: cannot lstat 'Library/Homebrew/os/mac/pkgconfig/11.0/._libffi.pc': No such file or directory
Error: superclass must be an instance of Class (given an instance of Module)
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/resource.rb:12:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/software_spec.rb:5:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/formula.rb:21:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/formula_installer.rb:4:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/cask/installer.rb:5:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/cmd/install.rb:6:in `<top (required)>'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/commands.rb:37:in `valid_internal_cmd?'
/Volumes/Other/pinoki/bin/homebrew/Library/Homebrew/brew.rb:65:in `<main>'
Do not report this issue: you are running in an unsupported configuration.
(base) <<PINOKIO_SHELL>>
```
