### ISSUE TITLE
ENOENT: no such file or directory, stat 'C:\pinokio\api\fooocus.git\{{input.event[0]}}'

### ISSUE THREAD

**Issue by moobond** [pinokiocomputer/pinokio#219]
there is error when installed Fooocus on pinokio

![2](https://github.com/user-attachments/assets/848d5b33-d469-40cb-86c3-92f3ea0f8898)
![1](https://github.com/user-attachments/assets/139c6b33-e87b-4601-8fb7-f5f8a00b31b9)

**Comment by tomasris** [comment]
ENOENT: no such file or directory, stat ‘С:\pinokio\api\lgm\{{input.event[0]}}’ usually means that the package was not installed correctly. usually it uses CUDA compiler of the system (I have 12.6), and the package needs older packages (11.8 for example).

**Comment by stephabauva** [comment]
I fixed the issue using Claude.dev on VSCode, I downloaded the GitHub repo on my machine (Mac) and I asked Claude.dev to do the installation, it looked into the files, installed things, found some errors and fixed them, it executed the app, I had to agree on the license by typing 'agree' in the terminal, and it opened the electron app, it's working now :)

**Comment by dulanyw** [comment]
Encountered the same issue with multiple Pinokio applications. Resolved by editing the default directory in the "Save as" dialog to remove the ".git" suffix at the end. For example, with this issue, instead of saving as "fooocus.git", save as "fooocus".

(Note: also similar to issue here: https://github.com/pinokiocomputer/pinokio/issues/206)
![image](https://github.com/user-attachments/assets/d90fb8b1-3011-40b6-b45e-ca1ee1932679)
![image](https://github.com/user-attachments/assets/52413f57-f561-47ac-acb6-716bf9b0e95b)

**Comment by lior007** [comment]
> Encountered the same issue with multiple Pinokio applications. Resolved by editing the default directory in the "Save as" dialog to remove the ".git" suffix at the end. For example, with this issue, instead of saving as "fooocus.git", save as "fooocus".
> 
> (Note: also similar to issue here: #206) ![image](https://private-user-images.githubusercontent.com/15172458/371675933-d90fb8b1-3011-40b6-b45e-ca1ee1932679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjI0NjIsIm5iZiI6MTcyODMyMjE2MiwicGF0aCI6Ii8xNTE3MjQ1OC8zNzE2NzU5MzMtZDkwZmI4YjEtMzAxMS00MGI2LWI0NWUtY2ExZWUxOTMyNjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE3MjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNjY4ZWNlNzE5NTgwODBlMWNiMmI1YzcwMjUzYTA5ZTA4MjQwOTEwMGMxN2IzNDZiNjhlNzJiY2E2YjI2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WVFmaXTf5qSEAJ-7HvLtXW3-RliL2IRbNZfQ9o_mwf4) ![image](https://private-user-images.githubusercontent.com/15172458/371676022-52413f57-f561-47ac-acb6-716bf9b0e95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjI0NjIsIm5iZiI6MTcyODMyMjE2MiwicGF0aCI6Ii8xNTE3MjQ1OC8zNzE2NzYwMjItNTI0MTNmNTctZjU2MS00N2FjLWFjYjYtNzE2YmY5YjBlOTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE3MjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNGRhMzQ5YjBiNzlkMTRlYTQ4NzU5YWFjMGY0OGY1MDk4MmQwYjI5NzM1YjZkOGUzZWEyZjlkYWM0YjczYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jsNaP0MI0Vi2VRq9CCpPgrgi7FtWFLsWIE0dCjwVXLU)

dont wwork for me

**Comment by duckie1970** [comment]
> Encountered the same issue with multiple Pinokio applications. Resolved by editing the default directory in the "Save as" dialog to remove the ".git" suffix at the end. For example, with this issue, instead of saving as "fooocus.git", save as "fooocus".
> 
Tried this and still got the same error. I alrso removed and re-installed from scratch including clearing Pinokio's cache and bin folders. Any tips for a non-technical user?
![image](https://github.com/user-attachments/assets/f5e43b3e-6a3d-45ff-b45d-e394e22d0613)

**Comment by fotodisk** [comment]
> Tried this and still got the same error. I alrso removed and re-installed from scratch including clearing Pinokio's cache and bin folders. Any tips for a non-technical user?
![F5TTS](https://github.com/user-attachments/assets/80a3cca9-5121-4f2a-9001-de77a84e04b2)
I got the same error as https://github.com/duckie1970.

**Comment by likdagreat** [comment]
if you right click on the pinokio app and run the app as an admin it should fix the issue.

**Comment by davideuler** [comment]
The same error, couldn't get any apps to run. I've test 5 apps. All went through the same error. on mac m1.

**Comment by likdagreat** [comment]
1 close out pinokio
2 right click pinokio app or icon
3 look for properties
4 look for run as administrator (preferably the check box that will always
run the app as admin
5start app

**Comment by guvier** [comment]
Hi, I’m facing the same problem, but I don’t need to fix it. I only need this for a school assignment that’s due on Sunday, 10/27/2024. I have to create a comic story and already have the plot. I’m here to ask for help from anyone with this tool working who could help me. I’m 17, Brazilian, and it’s for a school project. If anyone sees this before the due date, please message me on Instagram so I can respond and send the story I need the AI to create. My Instagram is @ogusvieira, and I have a few followers. Thanks in advance!

**Comment by StylizeR** [comment]
Had this error multiple times when clicking 'stop' in the terminal of the running app.
In terminal there was an error that the file cannot be written since it's in use.

So to fix it I terminated Pinokio in task manager.
Then starting the app works again.

So, **Ctrl+Alt+Del > Task Manager > End task 'Pinokio' > Start Pinokio again > Fixed**.

Probably the reason why Administrator works for some, since it has more permission to write?

**Comment by pip-bln** [comment]
Same error here on a win-computer. I tried all the recommended tricks and none of them worked for me. That's why I now believe that the program is simply badly programmed.
Because apart from that, all possible LLMs and image programs that were installed directly without pinokio run smoothly and without any problems. I just wanted to give Pinokio a try and realized that I couldn't get past this error.

**Comment by Alexander-RPR** [comment]
> there is error when installed Fooocus on pinokio
> 
Spanish: Hola a todos el problema se soluciona instalando una versión de pytorch compatible con la versión CUDA que tengas instalada. Yo tengo CUDA 11.8
Al hacer lo que indico se solucionó el problema que tenía días sin resolver

**Comment by Annita2418** [comment]
Try saving it like this when installing:
![git](https://github.com/user-attachments/assets/91071a52-321d-4a8a-a794-8b0e23e43d94)

**Comment by mb719** [comment]
I'm still getting this as well, I'll try the removing .git thing

**Comment by Brackarnwar** [comment]
pinokio is unusable due to this error. Has anyone find the solution ?

**Comment by stryder981** [comment]
just give up.

**Comment by murattr53** [comment]
I updated the Pinocchio programme and it worked for me.

**Comment by phpdevroot** [comment]
ENOENT: no such file or directory, stat 'D:\pinokio\api\automatic1111.git\{{input.event[0]}}'

Apparently the same problem here.
NEW installation, new directory and the same problem.

OS Windows 10
16 RAM
RTX 570 graphics card - 6GB RAM

HD 500GB only for Pinokio

Terminal
`To create a public link, set `share=True` in `launch()`.
Startup time: 62.0s (prepare environment: 97.1s, initialize shared: 5.7s, other imports: 0.2s, setup gfpgan: 0.1s, list SD models: 0.6s, load scripts: 1.0s, initialize extra networks: 0.2s, create 
ui: 2.3s, gradio launch: 1.9s, add APIs: 1.2s).
Creating model from config: D:\pinokio\api\automatic1111.git\app\repositories\generative-models\configs\inference\sd_xl_base.yaml
D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\huggingface_hub\file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads alwa
ys resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "D:\pinokio\bin\miniconda\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "D:\pinokio\bin\miniconda\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\pinokio\bin\miniconda\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\pinokio\api\automatic1111.git\app\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "D:\pinokio\api\automatic1111.git\app\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\pinokio\api\automatic1111.git\app\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "D:\pinokio\api\automatic1111.git\app\modules\sd_models.py", line 856, in load_model
    load_model_weights(sd_model, checkpoint_info, state_dict, timer)
  File "D:\pinokio\api\automatic1111.git\app\modules\sd_models.py", line 466, in load_model_weights
    model.float()
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\lightning_fabric\utilities\device_dtype_mixin.py", line 88, in float
    return super().float()
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 990, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
  File "D:\pinokio\api\automatic1111.git\app\venv\lib\site-packages\torch\nn\modules\module.py", line 990, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
RuntimeError: Could not allocate tensor with 6553600 bytes. There is not enough GPU video memory available!


Stable diffusion model failed to load
Applying attention optimization: sub-quadratic... done.`

**Comment by Alexo88** [comment]
update pinokio program, works

**Comment by MariusCodeAcademy** [comment]
Had the same issue on Windows. 
I realised that the error I got was about the page file size being too small. 
I realised I installed it on the D drive. By default, Windows only has a page file on the main C drive. So, I added the page file to drive D, and the error is gone, and startup continues. google "windows increase page file size" and make the changes or reinstall to drive C
Hope it helps

**Comment by bigboss97** [comment]
> So, I added the page file to drive D, and the error is gone, and startup continues. google "windows increase page file size" and make the changes or reinstall to drive C Hope it helps

I added a paging file max size 32GB on my E-drive. It did proceed further. But it still ended of with the same error. What size did you use?

**Comment by hero-hz1999yt** [comment]
I arrived a little late, but what solved the problem for me was the following:

- In the terminal, I got the following error:
ImportError: libpng16-ef62451c.so.16.44.0: cannot open shared object file: No such file or directory

- In the WebUI, I got the same error:
ENOENT: no such file or directory, stat '/home/user_name/pinokio/api/fooocus.git/{{input.event[0]}}'

First, I typed the following command to enter the environment:
cd pinokio/api/fooocus.git/app/env/

Then, I added fish at the end because it's the command interpreter I use, but if you have bash or zsh, it's a matter of adding your own:
source bin/activate.fish

Then
pip list | grep cv

it printed
opencv-contrib-python-headless 4.10.0.84
opencv-python 4.11.0.86
opencv-python-headless 4.11.0.86

and updated the first package to the same version as the others, with the following command:
pip install opencv-contrib-python-headless==4.11.0.86

and it fixed it, lol

**Comment by TheXug** [comment]
I also spent a lot of time troubleshooting, and here's what worked for me (Ultimate-TTS-Studio, Linux Mint):

Find my CUDA path with
`which nvcc`

which returned
`/usr/bin/nvcc`

And, therefore, I updated the env section of start.js (in /home/myusername/Pinokio/api/Ultimate-TTS-Studio.git) to be
`env: { 
          "CUDA_HOME": "/usr",
          "PATH": ["/usr/bin", "$PATH"]
        },`

I had also installed cuda toolkit from commandline.

**Comment by billyjsubs** [comment]
im running om fedora 43 and get the same issues with a couple of model now...is there any fix for linux?
i got it working on windows with no problems

thx

**Comment by wormk3** [comment]
The Solve of this is: Just Run it Pinokio as Admin
