### ISSUE TITLE
Error Connection errored out.

### ISSUE THREAD

**Issue by SCNDL80** [pinokiocomputer/pinokio#227]
Hi,
I tried to install FluxWebUI but when I tried any prompt I get a "Error Connection errored out." after around 10 sec. I use it on an AMD laptop with a Vega 10 GPU. I tried to reinstall but get render anything.
Any help welcome.
![fluxwebui](https://github.com/user-attachments/assets/fda334c9-af1f-466c-b8ed-6bf5cedb0744)

**Comment by neveride84** [comment]
I have exactly the same issue with PCM (Phased Consistency Model):

![image](https://github.com/user-attachments/assets/b25a3109-5653-4f4c-a2f6-8fd5dc86c9cd)

I am on Windows 10 and RTX3080 (latest drivers). I installed Pinokio as per instruction (nothing sophisticated) with no errors that I am aware of. Please help.

The logs show:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 656, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\dependencies\utils.py", line 881, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\_compat.py", line 284, in get_model_fields
    return [
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\fastapi\_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2028, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2189, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2185, in <lambda>
    lambda source, handler: handler(source)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "D:\Programy\Pinokio\api\pcm.git\app\env\lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydan
tic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` o
therwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

**Comment by temium62** [comment]
Hi

Same problem with Whisper WebUi. 
All other progamms in Pinokio work fine.
Nvidia RTX 3080 12Go , latest versions of Windows and Nvidia Drivers.
