### ISSUE TITLE
Facefusion 3.0.0 Error

### ISSUE THREAD

**Issue by adnaniz** [pinokiocomputer/pinokio#233]
```
Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.  

V:\pinokio\api\facefusion-pinokio.git\facefusion>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate V:\pinokio\api\facefusion-
pinokio.git\.env && python facefusion.py run --ui-layouts benchmark

EnvironmentLocationNotFound: Not a conda environment: V:\pinokio\api\facefusion-pinokio.git\.env

Traceback (most recent call last):
  File "V:\pinokio\api\facefusion-pinokio.git\facefusion\facefusion.py", line 7, in <module>
    from facefusion import core
  File "V:\pinokio\api\facefusion-pinokio.git\facefusion\facefusion\core.py", line 8, in <module>
    from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, 
voice_extractor, wording
  File "V:\pinokio\api\facefusion-pinokio.git\facefusion\facefusion\content_analyser.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

V:\pinokio\api\facefusion-pinokio.git\facefusion>
[Start Local Sharing]

## [LOCAL NETWORK SHARING] Scan the QR code to open in any device

```

**Comment by adnaniz** [comment]
Solved after couple or reinstallation.

**Comment by Merzlota** [comment]
Hey, How did you solve that?
