### ISSUE TITLE
Missing libpng16

### ISSUE THREAD

**Issue by TommyV6** [pinokiocomputer/pinokio#254]
I`m trying to install fluxgym and got:
<<PINOKIO_SHELL>>eval "$(conda shell.bash hook)" && conda deactivate && conda deactivate && conda deactivate && conda activate base && source /mnt/ssd2tb/pinokio/api/fluxgym.git/env/bin/activate /mnt/ssd2tb/pinokio/api/fluxgym.git/env && python app.py

Traceback (most recent call last):
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/app.py", line 19, in <module>
    from library import flux_train_utils, huggingface_util
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/sd-scripts/library/flux_train_utils.py", line 17, in <module>
    from library import flux_models, flux_utils, strategy_base, train_util
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/sd-scripts/library/flux_utils.py", line 15, in <module>
    from library.utils import setup_logging, MemoryEfficientSafeOpen
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/sd-scripts/library/utils.py", line 13, in <module>
    import cv2
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/mnt/ssd2tb/pinokio/api/fluxgym.git/env/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/mnt/ssd2tb/pinokio/bin/miniconda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpng16-1bde1c40.so.16.43.0: cannot open shared object file: No such file or directory
(env) (base) <<PINOKIO_SHELL>>

I got libpng16 in system but in version extra/libpng 1.6.44-1
in webui i see only ENOENT: no such file or directory, stat '/mnt/ssd2tb/pinokio/api/fluxgym.git/{{input.event[0]}}'
I`m runing up-to-date Arch.

**Comment by top7** [comment]
the same for me

**Comment by JuanReagan** [comment]
Same problem on Ubuntu 22.04.5 LTS

**Comment by ibobak** [comment]
I am getting the same, Ubuntu 22.04

**Comment by ibobak** [comment]
I found a fix.  if you are using pinokio with fluxgym and with forge, then pay attention to the library  opencv_python

which is installed in both environments:
```
/home/YOUR_USER/ai/pinokio/api/fluxgym.git/env/ 
```
and in 
```
/home/YOUR_USER/ai/pinokio/api/stable-diffusion-webui-forge.git/app/venv/ 
```

If we do
```
source bin/activate
```

In each of them and then 
```
pip list | grep cv
```

then for fluxgym it will print
```

opencv-python             4.8.1.78
opencv-python-headless    4.10.0.84
```

If you do the same for stable-diffusion-webui-forge.git , it will print the same version - 4.10.0.84.    In this library the required so file  
libpng16-1bde1c40.so.16.43.0 is located.

So, the solution is to run the command
```
pip install opencv-python==4.10.0.84
```

in the gluxgym's environment, after which it starts working

**Comment by ibobak** [comment]
For developers:  it would be good if you explicitly set this version in the requirements.txt

**Comment by aero-create** [comment]
Only registered to say thank you. It worked!

**Comment by goffy76** [comment]
it actually worked :-) Now I just have to figure out how to make it run on the GPU and not the CPU :-/  Welcome to the pleasure of owning an AMD GPU

**Comment by szczyglo74** [comment]
Ibobak, thank you very much. Now it's working :)
