### ISSUE TITLE
XTTS error

### ISSUE THREAD

**Issue by Reno0vacio** [pinokiocomputer/pinokio#41]
Microsoft Windows [Version 10.0.22621.2506]
(c) Microsoft Corporation. Minden jog fenntartva.

C:\Users\Reno\pinokio\api\xtts.pinokio.git>
C:\Users\Reno\pinokio\api\xtts.pinokio.git>env\Scripts\activate env

(env) C:\Users\Reno\pinokio\api\xtts.pinokio.git>python app.py
 > Downloading model to C:\Users\Reno\pinokio\cache\XDG_DATA_HOME\tts\tts_models--multilingual--multi-dataset--xtts_v1
0.00iB [00:00, ?iB/s]
 > Model's license - CPML
 > Check https://coqui.ai/cpml.txt for more info.
Traceback (most recent call last):
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\app.py", line 13, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1")
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\api.py", line 81, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\api.py", line 185, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 161, in _load_tts_from_dir
    config = load_config(os.path.join(model_dir, "config.json"))
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\config\__init__.py", line 95, in load_config
    data = read_json_with_comments(config_path)
  File "C:\Users\Reno\pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\config\__init__.py", line 22, in read_json_with_comments
    data = json.loads(input_str)
  File "C:\Users\Reno\pinokio\bin\miniconda\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Reno\pinokio\bin\miniconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Reno\pinokio\bin\miniconda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

> I just install and run. 
(Win 11)

**Comment by MateiCatalin** [comment]
The solution I find:

1. Open (cmd) or PowerShell at the installed path of XTTS inside the virtual environment located at the following path: `pinokio\api\xtts.pinokio.git\env\Scripts`.

2. Run the command: `.\activate` to activate the virtual environment.

3. Uninstall the 'tts' package using the command: `pip uninstall tts`.

4. Upgrade pip by running: `python.exe -m pip install --upgrade pip`.

5. Install the 'tts' package again with the command: `pip install tts`.

6. Open the 'app.py' file located in `pinokio\api\xtts.pinokio.git\` using a text editor like Notepad.

7. In 'app.py,' around line 109, look for the word "info" inside `gr.Audio()`. When you find "info," delete the entire line that contains the "info" block.

8. Finally, from the Pinokio GUI, launch XTTS.

**Comment by Makhyoun** [comment]
To solve this problem just Download config.json file from
https://huggingface.co/coqui/XTTS-v1 
add to  \pinokio\cash\XDG_DATA_HOME\tts\tts\tts_models—multilingual—multi_dataset—xtts_v1

**Comment by Reno0vacio** [comment]
Now it seems like it's fixed.
