### ISSUE TITLE
<%=config.icon%> - Cannot read properties of undefined (reading 'icon')

### ISSUE THREAD

**Issue by Michal-Mikolas** [pinokiocomputer/pinokio#86]
After installing the newest version (`Pinokio-1.0.16-win32`) and creating the `helloworld` script from the tutorial, when I try to run it, it just shows an error: 

```
TypeError: C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\server\views\browser.ejs:326
    324|   <div class='header-top header-item'>
    325|     <div class='app-info'>
 >> 326|       <img src="<%=rawpath%>/<%=config.icon%>?raw=true"/>
    327|       <div><%=config.title%></div>
    328|     </div>
    329|   </div>

Cannot read properties of undefined (reading 'icon')
    at eval ("C:\\Users\\mikolas\\AppData\\Local\\Programs\\Pinokio\\resources\\app.asar\\node_modules\\pinokiod\\server\\views\\browser.ejs":23:32)
    at browser (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\express\lib\response.js:1039:7)
    at C:\Users\mikolas\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\server\index.js:1838:11
```

![Pinokio_eFOxMlToax](https://github.com/pinokiocomputer/pinokio/assets/900316/3e7c9bea-f9bc-4629-8b01-47d0fabd992a)

I use Windows 10 22H2.

**Comment by passenger2020** [comment]
similar issues happened to mac intell OS sonoma 14.2.1  :)

**Comment by slsah30** [comment]
I have the same issue with latest release. Anything I installed myself and new installs come up with this error on Windows 11.

**Comment by appsdevpk** [comment]
Same issue on windows 10

**Comment by cetindogu** [comment]
same for windows 11 22H2

**Comment by earthworldformal** [comment]
add a file of pinokio.js like this:

module.exports = {
  version: 1,
  title: "helloworld",
  description: "new script",
  icon: ""
}
<img width="515" alt="截屏2024-01-17 21 39 54" src="https://github.com/pinokiocomputer/pinokio/assets/153349994/a9bf8c4e-44cc-4b47-8c0e-f78d7dac3aca">
<img width="422" alt="截屏2024-01-17 21 40 14" src="https://github.com/pinokiocomputer/pinokio/assets/153349994/b946398f-9b53-444b-ada4-868b596c4d6f">

**Comment by cetindogu** [comment]
thank you @earthworldformal 
my pinokio.js file content is: added a menu item to start


```
module.exports = {
  version: 1,
  title: "helloworld",
  description: "List Directory script",
  icon: "icon.png",
  menu: async (kernel) => {
    return [
        {
          icon: "fa-solid fa-terminal",
          text: "List",
          href: "index.json",
        },
      ];
  },
};

```

**Comment by aletelecom** [comment]
I also have this exact problem, and none of the proposed solutions works. I have Windows 10 Home Single Language 22H2.

**Comment by Michal-Mikolas** [comment]
After two and half months still not fixed?
