### ISSUE TITLE
No module named 'numpy' in running facefusion

### ISSUE THREAD

**Issue by reinhartzzhang1** [pinokiocomputer/pinokio#867]
D:\pinokio\api\facefusion-pinokio.git\facefusion>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate D:\pinokio\api\facefusion-pinokio.git\.env && python facefusion.py run
WARNING: overwriting environment variables set in the machine
overwriting variable ['PATH']
Traceback (most recent call last):
  File "D:\pinokio\api\facefusion-pinokio.git\facefusion\facefusion.py", line 7, in <module>
    from facefusion import core
  File "D:\pinokio\api\facefusion-pinokio.git\facefusion\facefusion\core.py", line 6, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

**Comment by JRLane-CS** [comment]
It sounds like the numpy library/module hasn't been imported for use by python. You might try manually installing numpy using pip and see if this will act as a workaround until this is addressed, since it seems conda is having a problem with it.
