### ISSUE TITLE
Devika is not working in pinokio

### ISSUE THREAD

**Issue by gokulcoder7** [pinokiocomputer/pinokio#871]
When I pressed select search engine, it's not opening

**Comment by gokulcoder7** [comment]
######################################################################
#
# group: F:\pinokio\api\devika.git\start.js
# id: 42c56a2f-f597-411a-91df-3ce4b154571f
# index: 0
# cmd: conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && F:\pinokio\api\devika.git\app\env\Scripts\activate F:\pinokio\api\devika.git\app\env && python devika.py
# timestamp: 23/12/2024, 5:42:59 pm (1734955979355)

Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

F:\pinokio\api\devika.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && F:\pinokio\api\devika.git\app\env\Scripts\activate F:\pinokio\api\devika.git\app\env && python devika.py
24.12.23 17:42:40: root: INFO   : Initializing Devika...
24.12.23 17:42:40: root: INFO   : checking configurations...
24.12.23 17:42:40: root: INFO   : Initializing Prerequisites Jobs...
24.12.23 17:42:51: root: INFO   : Loading sentence-transformer BERT models...
24.12.23 17:42:54: root: INFO   : BERT model loaded successfully.
Traceback (most recent call last):
  File "F:\pinokio\api\devika.git\app\devika.py", line 24, in <module>
    from src.agents import Agent
  File "F:\pinokio\api\devika.git\app\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "F:\pinokio\api\devika.git\app\src\agents\agent.py", line 1, in <module>
    from .planner import Planner
  File "F:\pinokio\api\devika.git\app\src\agents\planner\__init__.py", line 1, in <module>
    from .planner import Planner
  File "F:\pinokio\api\devika.git\app\src\agents\planner\planner.py", line 3, in <module>
    from src.llm import LLM
  File "F:\pinokio\api\devika.git\app\src\llm\__init__.py", line 1, in <module>
    from .llm import LLM
  File "F:\pinokio\api\devika.git\app\src\llm\llm.py", line 11, in <module>
    from .mistral_client import MistralAi
  File "F:\pinokio\api\devika.git\app\src\llm\mistral_client.py", line 2, in <module>
    from mistralai.models.chat_completion import ChatMessage
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'

(env) (base) F:\pinokio\api\devika.git\app>

######################################################################
#
# group: F:\pinokio\api\devika.git\start.js
# id: 507aa919-43a9-418e-8127-afc9b0b2b22f
# index: 0
# cmd: conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && npm run dev
# timestamp: 23/12/2024, 5:44:08 pm (1734956048285)

Microsoft Windows [Version 10.0.22631.4602]
(c) Microsoft Corporation. All rights reserved.

F:\pinokio\api\devika.git\app\ui>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && npm run dev

> ui@0.0.1 dev
> vite dev


  VITE v5.4.11  ready in 2444 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
