### ISSUE TITLE
Comfyui Download Models Error: Response status was 416

### ISSUE THREAD

**Issue by Mickeyto** [pinokiocomputer/pinokio#90]
Apple M2

Download Error:

[Redirected] 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/svd_xt.safetensors?download=true' => 'https://cdn-lfs-us-1.huggingface.co/repos/6e/59/6e594adc90884e0f59c5249f166a20166135ccab3a168d824ca8ef3bc5512e8c/b2652c23d64a1da5f14d55011b9b6dce55f2e72e395719f1cd1f8a079b00a451?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27svd_xt.safetensors%3B+filename%3D%22svd_xt.safetensors%22%3B&Expires=1705304157&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwNTMwNDE1N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmh1Z2dpbmdmYWNlLmNvL3JlcG9zLzZlLzU5LzZlNTk0YWRjOTA4ODRlMGY1OWM1MjQ5ZjE2NmEyMDE2NjEzNWNjYWIzYTE2OGQ4MjRjYThlZjNiYzU1MTJlOGMvYjI2NTJjMjNkNjRhMWRhNWYxNGQ1NTAxMWI5YjZkY2U1NWYyZTcyZTM5NTcxOWYxY2QxZjhhMDc5YjAwYTQ1MT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=bx7ltNYRcJWnPrjb9wLznXgG6CYzBqjtd56-WeXdx-lCk2pX1TlU6V-g2mOSr2ktgsfd%7E4sAyKWRV%7EG8gC7rooptD-eR8Zf2yUbPNdms4S5zT1CWwfNcJDB8wX9uHPdC5mM1y0c2vuqvyId8fm2C0L6n-On55VIEQ6stuhEXNHTEG2ls8OKdoNVRWG3dEZpWDTkhO2pKoEnQ20A%7EB5ARCDq3TMUvcgN6DSrDLfc0Ca8IgWjJGKMwjkE4fP3QI-y5xZ7-Ml9%7Eih-hQpDuvbBEo5TwWpu5%7EJrY02dblORSxCUuiPccRrfYX9wPZ1cMZEBL7Q1HjVUBBZnuK9BcuzUWxw__&Key-Pair-Id=KCD77M1F0VK2B'

[State changed] RESUMED

[State changed] FAILED

Download Error Error: Response status was 416
    at ClientRequest.<anonymous> (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/node-downloader-helper/dist/index.js:1:9499)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  status: 416,
  body: ''
}
Download Failed Error: Response status was 416
    at ClientRequest.<anonymous> (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/node-downloader-helper/dist/index.js:1:9499)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  status: 416,
  body: ''
}

**Comment by alxdrf** [comment]
same problem
Apple M1
