### ISSUE TITLE
"Hello world" example does not work

### ISSUE THREAD

**Issue by rowild** [pinokiocomputer/pinokio#98]
Following the Getting Started tutorial, the very first example – "hello world" – throughs this error on a Mac m2 32GB:

```sh
TypeError: /Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/pinokiod/server/views/browser.ejs:326
    324|   <div class='header-top header-item'>
    325|     <div class='app-info'>
 >> 326|       <img src="<%=rawpath%>/<%=config.icon%>?raw=true"/>
    327|       <div><%=config.title%></div>
    328|     </div>
    329|   </div>

Cannot read properties of undefined (reading 'icon')
    at eval ("/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/pinokiod/server/views/browser.ejs":23:32)
    at browser (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:274:36)
    at exports.renderFile [as engine] (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/view.js:135:8)
    at tryRender (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/application.js:657:10)
    at Function.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/response.js:1039:7)
    at /Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/pinokiod/server/index.js:1838:11
```

**Comment by CoderK** [comment]
I have the same issue.
- Apple M1 Pro
- Mac OS 14.1.1(23B81)

```
    324|   <div class='header-top header-item'>
    325|     <div class='app-info'>
 >> 326|       <img src="<%=rawpath%>/<%=config.icon%>?raw=true"/>
    327|       <div><%=config.title%></div>
    328|     </div>
    329|   </div>

Cannot read properties of undefined (reading 'icon')
    at eval ("/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/pinokiod/server/views/browser.ejs":23:32)
    at browser (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:274:36)
    at exports.renderFile [as engine] (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/view.js:135:8)
    at tryRender (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/application.js:657:10)
    at Function.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/express/lib/response.js:1039:7)
    at /Applications/Pinokio.app/Contents/Resources/app.asar/node_modules/pinokiod/server/index.js:1838:11
```

**Comment by billh93** [comment]
I get the same error. 
On a M2, Macbook Air, MacOS Ventura 13.3.1

Pinkokio Version 1.0.16 (1.0.16)

**Comment by GaoCan702** [comment]
I get the same error too

**Comment by adoddletranscriptioncleanup** [comment]
Same error on Windows.

**Comment by matthewkogan** [comment]
Same error on Windows.

**Comment by echeadle** [comment]
I get the same error on linux.

**Comment by AlexeyPodd** [comment]
Same error on linux, was using .deb and .AppImage. Is there any way to make it work?
