### ISSUE TITLE
False "not installed"

### ISSUE THREAD

**Issue by Fed13** [pinokiocomputer/pinokio#99]
I tried installing MAGNeT (not sure if it's important) using Pinokio, and the screen says "installation required" marking everything (conda, git, zip, etc.) but "registry" as "not installed".
And I definitely know I have git installed.
This makes me afraid to proceed in the sense - since it misidentifies stuff as not installed, could it break something when trying to install something that is already there?

**Comment by guyjames** [comment]
I have the same issue. I had all the required dependencies installed already, conda, git etc. But it insists on installing them again, which is ok if it works I suppose. But it only installs conda, then once it's installed git it doesn't recognise that it's installed, so it won't perform the following install steps.

No obvious error in the logs, just repeats this:
`
 termination_prompt_re: /~\/pinokio\/bin >[ \r\n]*$/g,
  cleaned: '\r\n' +
    '    ___eltopo@eltopo\r\n' +
    '   (.. |osGaruda Linux\r\n' +
    '   (<> |hostMS-7B46 2.0\r\n' +
    '  / __  \\kernel6.7.0-zen3-1-zen\r\n' +
    ' ( /  \\ /|uptime24m\r\n' +
    '_/\\ __)/_)pkgs1907\r\n' +
    '\\/-____\\/memory6590M / 15861M\r\n' +
    '\r\n' +
    '\r\n' +
    '~/pinokio/bin \r\n' +
    '> eval "$(conda shell.bash hook)" && conda activate base && conda install -y -c conda-forge git git-lfs\r\n' +
    'Channels:\r\n' +
    ' - conda-forge\r\n' +
    ' - defaults\r\n' +
    'Platform: linux-64\r\n' +
    'Collecting package metadata (repodata.json): done\r\n' +
    'Solving environment: done\r\n' +
    '\r\n' +
    '# All requested packages already installed.\r\n' +
    '\r\n' +
    '\r\n' +
    '~/pinokio/bin took 14s \r\n' +
    '> ',
  line: '    ___eltopo@eltopo   (.. |osGaruda Linux   (<> |hostMS-7B46 2.0  / __  \\kernel6.7.0-zen3-1-zen ( /  \\ /|uptime24m_/\\ __)/_)pkgs1907\\/-____\\/memory6590M / 15861M~/pinokio/bin > eval "$(conda shell.bash hook)" && conda activate base && conda install -y -c conda-forge git git-lfsChannels: - conda-forge - defaultsPlatform: linux-64Collecting package metadata (repodata.json): doneSolving environment: done# All requested packages already installed.~/pinokio/bin took 14s > ',
  test: null`

**Comment by b03a** [comment]
I do have the same issue.

The error message as following

Microsoft Windows [版本 10.0.19045.3930]
(c) Microsoft Corporation. 著作權所有，並保留一切權利。

D:\pinokio\bin>conda_hook && conda activate base && conda install -y -c conda-forge git git-lfs
Traceback (most recent call last):
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main.py", line 51, in main_subshell
    from .conda_argparse import do_call, generate_parser, generate_pre_parser
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\conda_argparse.py", line 50, in <module>
    from .main_create import configure_parser as configure_parser_create
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main_create.py", line 11, in <module>
    from ..notices import notices
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\__init__.py", line 3, in <module>
    from .core import notices  # noqa: F401
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\core.py", line 14, in <module>
    from . import cache, fetch, views
Microsoft Windows [版本 10.0.19045.3930]
(c) Microsoft Corporation. 著作權所有，並保留一切權利。

D:\pinokio\bin>conda_hook && conda activate base && conda install -y -c conda-forge 7zip
Traceback (most recent call last):
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main.py", line 51, in main_subshell
    from .conda_argparse import do_call, generate_parser, generate_pre_parser
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\conda_argparse.py", line 50, in <module>
    from .main_create import configure_parser as configure_parser_create
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main_create.py", line 11, in <module>
    from ..notices import notices
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\__init__.py", line 3, in <module>
    from .core import notices  # noqa: F401
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\core.py", line 14, in <module>
    from . import cache, fetch, views
Microsoft Windows [版本 10.0.19045.3930]
(c) Microsoft Corporation. 著作權所有，並保留一切權利。

D:\pinokio\bin>conda_hook && conda activate base && conda install nodejs -y -c conda-forge
Traceback (most recent call last):
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main.py", line 51, in main_subshell
    from .conda_argparse import do_call, generate_parser, generate_pre_parser
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\conda_argparse.py", line 50, in <module>
    from .main_create import configure_parser as configure_parser_create
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main_create.py", line 11, in <module>
    from ..notices import notices
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\__init__.py", line 3, in <module>
    from .core import notices  # noqa: F401
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\core.py", line 14, in <module>
    from . import cache, fetch, views
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\notices\cache.py", line 25, in <module>
    from ..utils import ensure_dir_exists
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\utils.py", line 23, in <module>
    from .gateways.disk.read import compute_sum
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\gateways\disk\read.py", line 31, in <module>
    from ...exceptions import CondaUpgradeError, CondaVerificationError, PathNotFoundError
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exceptions.py", line 15, in <module>
    import requests
  File "D:\pinokio\bin\miniconda\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\connectionpool.py", line 15, in <module>
    from ._request_methods import RequestMethods
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 284, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 294, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pinokio\bin\miniconda\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\cli\main.py", line 128, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 388, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 20, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exception_handler.py", line 51, in handle_exception        
    from .exceptions import (
  File "D:\pinokio\bin\miniconda\lib\site-packages\conda\exceptions.py", line 15, in <module>
    import requests
  File "D:\pinokio\bin\miniconda\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\__init__.py", line 17, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\connectionpool.py", line 15, in <module>
    from ._request_methods import RequestMethods
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 284, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "D:\pinokio\bin\miniconda\lib\site-packages\urllib3\response.py", line 294, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'

![2024-02-13 042338](https://github.com/pinokiocomputer/pinokio/assets/159829111/2c7ed771-fbc7-42b9-84d9-84d37bf35f13)
![2024-02-13 042420](https://github.com/pinokiocomputer/pinokio/assets/159829111/60b73cf4-8023-4bef-872d-eb9ba7a68e73)

**Comment by StarkDylan** [comment]
same issue/

**Comment by foundationer** [comment]
Same issue here, both on Windows 11 and Arch Linux. I haven't attempted to install the already installed packages.

**Comment by roaminmatt** [comment]
same issue windows 10

**Comment by CaptainKokomo** [comment]
and mine said it today. Anyone got an answer short of delete and reinstall? I lost a years worth of images last time I did that.

**Comment by 6Morpheus6** [comment]
> and mine said it today. Anyone got an answer short of delete and reinstall? I lost a years worth of images last time I did that.

This installation loop happens because conda couldn't be installed. Hence everything else fails as well, since the requirements are installed by conda.
In most cases it is enough to delete the folder `.\pinokio\bin`
This will not delete or harm any of your installed apps since they are installed in `.\pinokio\api`
The latest version of Pinokio provides fixes related to conda and your base environment.
Please install the latest version from here [program.pinokio](https://program.pinokio.computer/#/?id=install) delete `.\pinokio\bin` and try to install your app again. This should fix the majority of these issues.

**Comment by takimdigital** [comment]
### I finally fixed the issue. Here's what worked for me:

1. **Remove the Existing Installation:**
   - Delete the folder `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda` if that’s where you installed it).

2. **Download the Latest Miniconda:**
   - Go to the [Miniconda download page](https://docs.anaconda.com/miniconda/#miniconda-latest-installer-links) and download the latest installer for your system.

3. **Install Miniconda:**
   - During the installation, make sure to keep the original path as `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda`). Do **not** change it to `D:\pinokio\bin\miniconda3` or any other name.

4. **Set Up the PATH Environment Variable:**
   - **Open System Properties:**
     - Press `Win + R`, type `sysdm.cpl`, and press `Enter`.
   - **Navigate to Environment Variables:**
     - In the System Properties window, go to the `Advanced` tab.
     - Click on `Environment Variables`.
   - **Edit the PATH Variable:**
     - If you're setting this up for your user account, select the `Path` variable under `User Variables for <YourUsername>`.
     - If you want to set this up for all users, select the `Path` variable under `System Variables`.
   - **Add the Miniconda Paths:**
     - Click on `New` and add the following paths one by one:
       - `D:\pinokio\bin\miniconda\`
       - `D:\pinokio\bin\miniconda\Scripts\`
       - `D:\pinokio\bin\miniconda\Library\bin\` (if needed)
     - If you installed Miniconda in `C:\`, replace `D:\` with `C:\` in the above paths.
   - **Save the Changes:**
     - Click `OK` to close the Edit Environment Variable dialog.
     - Click `OK` to close the Environment Variables window.
     - Click `OK` to close the System Properties window.

5. **Restart Your Computer:**
   - Restart your computer to ensure the changes take effect.

6. **Test the Installation:**
   - Open Command Prompt and type `conda --version` to verify that Miniconda is correctly installed and functioning.

**Comment by richiepic** [comment]
I had the same issue with the installation as I changed all of the paths to a different drive including the default one (home). 
Then I left pinokio on the default location but the rest of the links went to another drive. (Advance settings)

**Comment by joewithag** [comment]
all of my problems were gone when i uninstalled everything and did a new install in the default folder

**Comment by mago-kamar** [comment]
> ### I finally fixed the issue. Here's what worked for me:
> 
>     1. **Remove the Existing Installation:**
>        
>        * Delete the folder `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda` if that’s where you installed it).
> 
>     ......

>        * Restart your computer to ensure the changes take effect.
> 
>     6. **Test the Installation:**
>        
>        * Open Command Prompt and type `conda --version` to verify that Miniconda is correctly installed and functioning.

@takimdigital you're my hero :)
Thanks a lot for your solution

**Comment by takimdigital** [comment]
@mago-kamar  I'm really happy that i was able to help you ,  enjoy your day .

**Comment by alioslo7** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/431f6231-1de0-4eed-8107-84237fa7178c)
I tried directing it to the installation location and followed all the methods mentioned here, but unfortunately, all tasks fail

**Comment by blissiraDC** [comment]
> ### I finally fixed the issue. Here's what worked for me:
> 1. **Remove the Existing Installation:**
>    
>    * Delete the folder `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda` if that’s where you installed it).
> 2. **Download this version of Miniconda:**
>    
>    * https://repo.anaconda.com/miniconda/Miniconda3-py310_24.5.0-0-Windows-x86_64.exe
> 3. **Install Miniconda:**
>    
>    * During the installation, make sure to keep the original path as `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda`). Do **not** change it to `D:\pinokio\bin\miniconda3` or any other name.
> 4. **Set Up the PATH Environment Variable:**
>    
>    * **Open System Properties:**
>      
>      * Press `Win + R`, type `sysdm.cpl`, and press `Enter`.
>    * **Navigate to Environment Variables:**
>      
>      * In the System Properties window, go to the `Advanced` tab.
>      * Click on `Environment Variables`.
>    * **Edit the PATH Variable:**
>      
>      * If you're setting this up for your user account, select the `Path` variable under `User Variables for <YourUsername>`.
>      * If you want to set this up for all users, select the `Path` variable under `System Variables`.
>    * **Add the Miniconda Paths:**
>      
>      * Click on `New` and add the following paths one by one:
>        
>        * `D:\pinokio\bin\miniconda\`
>        * `D:\pinokio\bin\miniconda\Scripts\`
>        * `D:\pinokio\bin\miniconda\Library\bin\` (if needed)
>      * If you installed Miniconda in `C:\`, replace `D:\` with `C:\` in the above paths.
>    * **Save the Changes:**
>      
>      * Click `OK` to close the Edit Environment Variable dialog.
>      * Click `OK` to close the Environment Variables window.
>      * Click `OK` to close the System Properties window.
> 5. **Restart Your Computer:**
>    
>    * Restart your computer to ensure the changes take effect.
> 6. **Test the Installation:**
>    
>    * Open Command Prompt and type `conda --version` to verify that Miniconda is correctly installed and functioning.

ABSOLUTE LEGEND! Thank You!

**Comment by meikodunois** [comment]
still and issue for me, always asks me to install most of the requeriments, i already have every requeriment installed, i contacted pinokio support they couldn't help me either. I tried almost 6 different versions of pinokio (included the betas), i uninstalled the program with revo uninstaller, i cleaned the registry, i tried everything over and over again and no luck, i added to the path the folders inside miniconda, etc etc. Nothing works. When i do a  clean installation everything seems to work, but if i close the program and open it again it ask me to install the requeriments every single time even if i do a manual installation.

**Comment by tomerbarkan** [comment]
May 2025, this is still an issue. Tried Pinokio for the first time, and when I try to install anaything all the dependencies I know I have (git, py, vs, node) appear as not installed. Guess I'm going to have to do my installations manually.

**Comment by Milor123** [comment]
> ### I finally fixed the issue. Here's what worked for me:
> 
>     1. **Remove the Existing Installation:**
>        
>        * Delete the folder `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda` if that’s where you installed it).
> 
>     2. **Download this version of Miniconda:**
>        
>        * https://repo.anaconda.com/miniconda/Miniconda3-py310_24.5.0-0-Windows-x86_64.exe
> 
>     3. **Install Miniconda:**
>        
>        * During the installation, make sure to keep the original path as `D:\pinokio\bin\miniconda` (or `C:\pinokio\bin\miniconda`). Do **not** change it to `D:\pinokio\bin\miniconda3` or any other name.
> 
>     4. **Set Up the PATH Environment Variable:**
>        
>        * **Open System Properties:**
>          
>          * Press `Win + R`, type `sysdm.cpl`, and press `Enter`.
>        * **Navigate to Environment Variables:**
>          
>          * In the System Properties window, go to the `Advanced` tab.
>          * Click on `Environment Variables`.
>        * **Edit the PATH Variable:**
>          
>          * If you're setting this up for your user account, select the `Path` variable under `User Variables for <YourUsername>`.
>          * If you want to set this up for all users, select the `Path` variable under `System Variables`.
>        * **Add the Miniconda Paths:**
>          
>          * Click on `New` and add the following paths one by one:
>            
>            * `D:\pinokio\bin\miniconda\`
>            * `D:\pinokio\bin\miniconda\Scripts\`
>            * `D:\pinokio\bin\miniconda\Library\bin\` (if needed)
>          * If you installed Miniconda in `C:\`, replace `D:\` with `C:\` in the above paths.
>        * **Save the Changes:**
>          
>          * Click `OK` to close the Edit Environment Variable dialog.
>          * Click `OK` to close the Environment Variables window.
>          * Click `OK` to close the System Properties window.
> 
>     5. **Restart Your Computer:**
>        
>        * Restart your computer to ensure the changes take effect.
> 
>     6. **Test the Installation:**
>        
>        * Open Command Prompt and type `conda --version` to verify that Miniconda is correctly installed and functioning.

I've reinstalled, delete all C folders of pinokio, and add the location to path in virtual enviroments, but the pinkio keep in loop installing conda and searching `conda_hook`.

what should i do guys, I am in windows 11 with 3.8.0 pinokio

**Comment by mr-szgz** [comment]
can confirm @takimdigital solution works in pinokio 3.9.0

**Comment by YamamotoKaderate** [comment]
I tried to apply takimdigital solution with Miniconda3-py310_25.1.1-2-Windows-x86_64.exe that pinokio was requesting. Don't know what it change, but for it to work I had to do the install for everyone on the computer, not just for my user.

**Comment by Foadsf** [comment]
I'm experiencing the same issue and have submitted a related report at [here](https://github.com/pinokiofactory/open-webui/issues/14)

After reviewing all the solutions in this thread, I think there are two fundamental design issues that need to be addressed:

## 1. Dependency Detection Should Be More Flexible

The current approach requiring everything to be installed under `C:\pinokio\bin` is problematic for users who already have working installations via standard package managers:

- **conda** via Miniconda/Anaconda in standard locations
- **git** via official Windows installer  
- **node** via FNM, NVM, or official installer
- **ffmpeg** via Chocolatey, Scoop, or manual installation
- **zip** via system utilities

These tools are properly installed, accessible via PATH, and fully functional. Pinokio should be able to detect and use existing installations rather than forcing users to reinstall everything in its isolated directory.

## 2. Need for CLI Interface for Debugging

The lack of a CLI makes troubleshooting these issues unnecessarily difficult. A CLI would enable:

- **Verbose dependency checking**: `pinokio check --verbose` to see exactly what paths are being searched
- **Manual path configuration**: `pinokio config set conda-path "C:\Users\...\miniconda3"`  
- **Dependency override**: `pinokio install --skip-deps` to bypass detection for advanced users
- **Debug logging**: Better visibility into what the detection mechanism is actually doing

## Suggested Improvements

1. **Detection priority**: Check system PATH first, then fallback to Pinokio's bin directory
2. **Configuration file**: Allow users to specify custom paths for dependencies  
3. **CLI tools**: Provide command-line interface for debugging and configuration
4. **Better error messages**: Show exactly what paths were searched and why detection failed

The current workaround of reinstalling everything under `C:\pinokio\bin` works, but it's not user-friendly for people who have carefully maintained development environments with existing package managers.

Would the Pinokio team consider implementing more flexible dependency detection and CLI tools to make troubleshooting easier?

**Comment by arnookie** [comment]
To fix this make sure you don't have miniconda,  Ancona make sure you uninstall any conda apps. Reboot. Then delete the bin file :/pinokio/bin don't forget put your drive letter pinokio is installed to. then uninstall pinokio app via programs and features. Reboot then reinstall pinokio. 
From this point you should be able to install any apps within pinokio without issues.

**Comment by davidstarpro-pixel** [comment]
Hello, I have conda 25.5.1, added 140.82.114.4 github.com to hosts file, added enviroment variables for C:\pinokio\bin\miniconda\, etc. When try install F5-TTS, pinokio gives me error: 
C:\pinokio\api>conda_hook & conda deactivate & conda deactivate & conda deactivate & conda activate base && git clone https://github.com/pinokiofactory/e2-f52tts.git e2-f52tts.git
Cloning into 'e2-f52tts.git'...
fatal: unable to access 'https://github.com/pinokiofactory/e2-f52tts.git/': Failed to connect to github.com port 443 after 69 ms: Could not connect to server
Someone have that bug and already fixed it?.

**Comment by davidstarpro-pixel** [comment]
Does GitHub block certain countries or regions?. Or is Pinokio not working due to unknown restrictions?
